version: '3.8'

services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: permissions_db
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2
    ports:
      - '4222:4222'
      - '8222:8222'
    command: ['-js', '-m', '8222']
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:8222/varz"]
      interval: 5s
      timeout: 5s
      retries: 5

  permissions-service:
    build: .
    environment:
      - NATS_URL=nats://nats:4222
      - PG_HOST=postgres
      - PG_USER=postgres
      - PG_PASSWORD=password
      - PG_DATABASE=permissions_db
      - PG_PORT=5432
    depends_on:
      postgres:
        condition: service_healthy
      nats:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data: